name: "pglockanalyze"
description: >
  Runs pglockanalyze against the provided migration files listed in
  `input_files` and posts the results in PR annotations.

branding:
  icon: "database"
  color: "blue"

inputs:
  db-host:
    description: "PostgreSQL host"
    required: false
    default: "localhost"

  db-port:
    description: "PostgreSQL port"
    required: false
    default: "5432"

  db-name:
    description: "Database name"
    required: false
    default: "pgladb"

  db-user:
    description: "Database user"
    required: false
    default: "pglauser"

  db-password:
    description: "Database password"
    required: false
    default: "pglapass"

  input_files:
    description: |
      New-line separated list of migration **file paths** to analyse. Each file
      is processed individually.
    required: true

  pglockanalyze-version:
    description: "Version of pglockanalyze to use (default: latest)"
    required: false

  cli-flags:
    description: "Additional pglockanalyze CLI flags (optional)"
    required: false


runs:
  using: "composite"

  steps:
    - name: Install Rust toolchain
      shell: bash
      run: |
        if ! command -v cargo >/dev/null; then
          curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
        fi

    - name: Install pglockanalyze
      shell: bash
      env:
        PGLA_VERSION: ${{ inputs.pgla-version }}
      run: |
        if [[ -n "$PGLA_VER" ]]; then
          cargo install pglockanalyze --locked --force --version "$PGLA_VERSION"
        else
          cargo install pglockanalyze --locked --force
        fi

    - name: Ensure jq is available
      shell: bash
      run: |
        if ! command -v jq >/dev/null; then
          sudo apt-get update -y
          sudo apt-get install -y jq
        fi

    - name: Run pglockanalyze and post annotations
      shell: bash
      env:
        DB_HOST:      ${{ inputs['db-host'] }}
        DB_PORT:      ${{ inputs['db-port'] }}
        DB_NAME:      ${{ inputs['db-name'] }}
        DB_USER:      ${{ inputs['db-user'] }}
        DB_PASS:      ${{ inputs['db-password'] }}
        INPUT_FILES:  ${{ inputs.input_files }}
        CLI_FLAGS:    ${{ inputs['cli-flags'] }}
      run: |
        "${{ github.action_path }}/scripts/run.sh"
