name: "pglockanalyze CI Action (composite)"
description: >
  Runs pglockanalyze against PostgreSQL schema migrations supplied
  either inline (`input_inline`) or as files (`input_files`), then
  posts inline PR comments describing the locks acquired.

branding:
  icon: "unlock"
  color: "blue"

########################
#        inputs        #
########################
inputs:
  db-host:
    description: "PostgreSQL host"
    required: false
    default: "localhost"

  db-port:
    description: "PostgreSQL port"
    required: false
    default: "5432"

  db-name:
    description: "Database name"
    required: false
    default: "pgladb"

  db-user:
    description: "Database user"
    required: false
    default: "pglauser"

  db-password:
    description: "Database password"
    required: false
    default: "pglapass"

  input_inline:          # ⬅️ renamed
    description: |
      **Inline DDL** statements to analyse.
      Supply multiple statements separated by new-lines.
    required: false

  input_files:           # ⬅️ renamed
    description: |
      New-line separated list of migration **file paths** (within the repo)
      to analyse.
    required: false

  cli-flags:
    description: "Additional pglockanalyze CLI flags (optional)"
    required: false

  github-token:
    description: "GitHub token with `pull-requests:write` permission"
    required: false
    default: "${{ github.token }}"

########################
#        runner        #
########################
runs:
  using: "composite"

  steps:
    - name: Install Rust toolchain
      shell: bash
      run: |
        if ! command -v cargo >/dev/null; then
          curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
        fi

    - name: Install pglockanalyze
      shell: bash
      run: |
        cargo install pglockanalyze --locked --force

    - name: Ensure jq is available
      shell: bash
      run: |
        if ! command -v jq >/dev/null; then
          sudo apt-get update -y
          sudo apt-get install -y jq
        fi

    - name: Run pglockanalyze and post comments
      shell: bash
      env:
        DB_HOST:      ${{ inputs.db-host }}
        DB_PORT:      ${{ inputs.db-port }}
        DB_NAME:      ${{ inputs.db-name }}
        DB_USER:      ${{ inputs.db-user }}
        DB_PASS:      ${{ inputs.db-password }}
        INLINE_DDL:   ${{ inputs.input_inline }}
        FILE_INPUTS:  ${{ inputs.input_files }}
        CLI_FLAGS:    ${{ inputs.cli-flags }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        "${{ github.action_path }}/scripts/run.sh"
