name: lock-check (self-test)

on:
  workflow_dispatch:          # manual trigger
  push:

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    # --- service container that supplies PostgreSQL ---
    services:
      db:
        image: postgres:16
        env:
          POSTGRES_USER: pglauser
          POSTGRES_PASSWORD: pglapass
          POSTGRES_DB: pgladb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4     # checks out *this* repo

      - name: Setup initial schema
        run: |
          PGPASSWORD=pglapass psql -h localhost -p 5432 -U pglauser -d pgladb -c "CREATE TABLE users (name VARCHAR);"

      - name: pglockanalyze
        uses: ./.github/actions/pglockanalyze-action   # <── relative path
        with:
          input_files: |
            foo.sql
            bar.sql
